# Generated by Django 3.2.10 on 2021-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='PasscreationDate',
            field=models.DateTimeField(null=True),
        ),
    ]
